name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: app.py
      FLASK_ENV: testing
      DATABASE_URL: sqlite:///test_tasks.db
      PORT: 5000

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask Flask-SQLAlchemy python-dotenv

      - name: Start Flask app
        run: |
          nohup flask run --host=0.0.0.0 --port=5000 &
          sleep 5

      - name: Health check
        run: |
          curl --fail http://localhost:5000/health
