name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: app.py
      FLASK_ENV: testing
      DATABASE_URL: sqlite:///test_tasks.db
      PORT: 5000

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask Flask-SQLAlchemy python-dotenv

      - name: Start Flask app in background
        run: |
          export FLASK_APP=app.py
          nohup python -m flask run --host=0.0.0.0 --port=5000 > flask.log 2>&1 &
          sleep 10

      - name: Health check
        run: |
          curl --retry 5 --retry-delay 2 --retry-connrefused --fail http://localhost:5000/health
