name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: app.py
      FLASK_ENV: testing
      DATABASE_URL: sqlite:///test_tasks.db
      PORT: 5000

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize migrations
        run: |
          flask db init || echo "Already initialized"
          flask db migrate --message "CI" || echo "No changes"
          flask db upgrade

      - name: Run health check
        run: |
          nohup flask run --host=0.0.0.0 --port=5000 &
          sleep 5
          curl --fail http://localhost:5000/health
